name: Generate livestreams
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install youtube-dl
      run: |
        sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: GLOBOPLAY
      run: |
        touch ./GLOBOPLAY.m3u8
        sudo cat >./GLOBOPLAY.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://globoplay.globo.com/v/10787238/editorial/d31f02a6-5363-47ee-9243-c9f7f5e5eac3/)
        EOL
    - name: CNN ESPAÑOL
      run: |
        touch ./CNNESPAÑOL.m3u8
        sudo cat >./CNNESPAÑOL.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl --geo-bypass-country VE -g https://www.youtube.com/c/cnnee/live)
        EOL
    - name: CBC News
      run: |
        touch ./CBCNews.m3u8
        sudo cat >./CBCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/canadian-news/cbc-news.html)
        EOL
    - name: Get euronews.m3u8
      run: |
        touch ./euronews.m3u8
        sudo cat >./euronews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g  https://www.youtube.com/watch?v=l8tzW5jRiyw)
        EOL
    - name: Get ALGUM.m3u8
      run: |
        touch ./ALGUM.m3u8
        sudo cat >./ALGUM.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.climaaovivo.com.br/sp/sao-paulo/sao-paulo-slaviero-essential-ibirapuera)
        EOL        
    - name: Get ALGUM2.m3u8
      run: |
        touch ./ALGUM2.m3u8
        sudo cat >./ALGUM2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.climaaovivo.com.br/sp/sao-paulo/alpha-sat-paulista-wall-street-sudoeste)
        EOL
    - name: Get ALGUM3.m3u8
      run: |
        touch ./ALGUM3.m3u8
        sudo cat >./ALGUM3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.climaaovivo.com.br/sp/sao-paulo/sao-paulo-slaviero-essential-moema)
        EOL
    - name: Get ALGUM4.m3u8
      run: |
        touch ./ALGUM4.m3u8
        sudo cat >./ALGUM4.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.climaaovivo.com.br/go/goiania-comfort-hotel-goiania)
        EOL
    - name: Get ALGUM5.m3u8
      run: |
        touch ./ALGUM5.m3u8
        sudo cat >./ALGUM5.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.climaaovivo.com.br/rj/rio-de-janeiro/rio-de-janeiro-cdesign-hotel)
        EOL       
    - name: Get ALGUM6.m3u8
      run: |
        touch ./ALGUM6.m3u8
        sudo cat >./ALGUM6.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.climaaovivo.com.br/rj/rio-de-janeiro/rio-de-janeiro-tuakaza)
        EOL        
    - name: Get ALGUM7.m3u8
      run: |
        touch ./ALGUM7.m3u8
        sudo cat >./ALGUM7.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.climaaovivo.com.br/rj/rio-de-janeiro/rio-de-janeiro-cdesign-hotel)
        EOL        
    - name: Get ALGUM8.m3u8
      run: |
        touch ./ALGUM8.m3u8
        sudo cat >./ALGUM8.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://vimeo.com/170691930)
        EOL                
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
