name: Generate livestreams
on:
  schedule:
    - cron: '0 0/2 * * *'
  workflow_dispatch:
jobs:
  workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
     - name: Install youtube-dl
       run: |
        sudo -H pip install --upgrade youtube-dl
