name: Generate livestreams
on:
  schedule:
    - cron: '0 0/2 * * *'
  workflow_dispatch:
jobs:
  workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
     - name: Install youtube-dl
       run: |
        sudo -H pip install --upgrade youtube-dl
     - name: RTVE 24h
       run: |
        mkdir "ES"
        cd ES
        touch ./24h.m3u8
        sudo cat >./24h.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/rtvenoticias/live)
        EOL
