name: Generate livestreams
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install youtube-dl
      run: |
        sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: RTVE 24h
      run: |
        touch ./24h.m3u8
        sudo cat >./24h.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/rtvenoticias/live)
        EOL
    - name: CBC News
      run: |
        touch ./CBCNews.m3u8
        sudo cat >./CBCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/canadian-news/cbc-news.html)
        EOL
    - name: Get euronews.m3u8
      run: |
        touch ./euronews.m3u8
        sudo cat >./euronews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl --get-thumbnail  https://www.youtube.com/watch?v=QCeNWinKkZg)
        EOL
    - name: Get ALGUM.m3u8
      run: |
        touch ./ALGUM.m3u8
        sudo cat >./ALGUM.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://radio.ufg.br/p/8051-radio-ao-vivo)
        EOL        
    - name: Get ALGUM2.m3u8
      run: |
        touch ./ALGUM2.m3u8
        sudo cat >./ALGUM2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.cxtv.com.br/tv-ao-vivo/iurd-tv)
        EOL
    - name: Get ALGUM3.m3u8
      run: |
        touch ./ALGUM3.m3u8
        sudo cat >./ALGUM3.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g https://www.cxtv.com.br/tv-ao-vivo/sic)
        EOL
    - name: Get ALGUM4.m3u8
      run: |
        touch ./ALGUM4.m3u8
        sudo cat >./ALGUM4.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(youtube-dl -g  https://diaonline.ig.com.br/camera-ao-vivo/praca-civica-goiania-go)
        EOL
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
        
        https://www.climaaovivo.com.br/sp/sao-paulo/sao-paulo-slaviero-essential-ibirapuera
        https://www.climaaovivo.com.br/sp/sao-paulo/alpha-sat-paulista-wall-street-sudoeste
        https://www.climaaovivo.com.br/sp/sao-paulo/sao-paulo-slaviero-essential-moema
        https://www.climaaovivo.com.br/rj/rio-de-janeiro/rio-de-janeiro-cdesign-hotel
        https://www.climaaovivo.com.br/rj/rio-de-janeiro/rio-de-janeiro-tuakaza
        https://www.climaaovivo.com.br/rj/rio-de-janeiro/rio-de-janeiro-cdesign-hotel
        https://www.climaaovivo.com.br/go/goiania-comfort-hotel-goiania)
