name: Get StreamLink Live m3u8
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install youtube-dl
       run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: RTVE 24h
       run: |
        touch ./24h.m3u8
        sudo cat >./24h.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/rtvenoticias/live)
        EOL
     - name: 7NN
       run: |
        touch ./7nn.m3u8
        sudo cat >./7nn.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://twitch.tv/7nntv)
        EOL
     - name: Libertad Digital
       run: |
        touch ./libertaddigital.m3u8
        sudo cat >./libertaddigital.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://dai.ly/xnm032)
        EOL
     - name: Dejate de Historias - Madrid
       run: |
        touch ./DH.m3u8
        sudo cat >./DH.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/channel/UChMCkc02GVSi89TrvhbRasA/live)
        EOL
     - name: A24
       run: |
        mkdir "AR"
        cd AR
        touch ./A24.m3u8
        sudo cat >./A24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/A24com/live)
        EOL
     - name: America
       run: |
        cd AR
        touch ./America.m3u8
        sudo cat >./America.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/americaenvivo/live)
        EOL
     - name: TVP Argentina
       run: |
        cd AR
        touch ./TVP.m3u8
        sudo cat >./TVP.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/TVPublicaArgentina/live)
        EOL
     - name: LN+
       run: |
        cd AR
        touch ./LNMas.m3u8
        sudo cat >./LNMas.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/LaNacionMas/live)
        EOL
     - name: C5N
       run: |
        cd AR
        touch ./C5N.m3u8
        sudo cat >./C5N.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/c5n/live)
        EOL
     - name: CNN
       run: |
        mkdir "US"
        cd US
        touch ./CNN.m3u8
        sudo cat >./CNN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/american/cnn-live.html)
        EOL
     - name: Weather Channel
       run: |
        cd US
        touch ./WeatherChannel.m3u8
        sudo cat >./WeatherChannel.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/featured/weather-channel.html)
        EOL
     - name: FBN
       run: |
        cd US
        touch ./FBN.m3u8
        sudo cat >./FBN.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/business/fox-business-network-fbn.html)
        EOL
     - name: CNBC
       run: |
        cd US
        touch ./CNBC.m3u8
        sudo cat >./CNBC.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/american/cnbc.html)
        EOL
     - name: NTV24
       run: |
        mkdir "JP"
        cd JP
        touch ./NTVNews24.m3u8
        sudo cat >./NTVNews24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/channel/UCuTAXTexrhetbOe3zgskJBQ/live)
        EOL
     - name: TBS News Dig
       run: |
        cd JP
        touch ./TBSNewsDig.m3u8
        sudo cat >./TBSNewsDig.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/tbsnews/live)
        EOL
     - name: NHK World News
       run: |
        cd JP
        touch ./NHKWorldNews.m3u8
        sudo cat >./NHKWorldNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://youtube.com/NHKWORLDJAPAN/live)
        EOL
     - name: CBC News
       run: |
        mkdir "CA"
        cd CA
        touch ./CBCNews.m3u8
        sudo cat >./CBCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(youtube-dl -g https://www.livenewsnow.com/canadian-news/cbc-news.html)
        EOL           
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
